import type { Metadata } from "next";
import "./globals.css";

import '@ant-design/v5-patch-for-react-19';
import "./globals.css";
import Layout, { Header, Content, Footer } from "antd/es/layout/layout";
import { Menu } from "antd";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Medical Booking",
  description: "Generated by create next app"
  //icons: '/favicon.png', 
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>)
{
    const items = [
        { key: "home", label: <Link href="/">Home</Link> },
        { key: "allorders" },
        { key: "neworder" },
        { key: "currentuser" },
        { key: "logout" }
    ]
  return (
      <html lang="en">
          <body>
              <Layout style={{ minHeight: '100vh' }}>
                  <Header>
                      <Menu
                          theme="dark"
                          mode="horizontal"
                          items={items}
                          style={{ flex: 1, minWidth: 0 }}
                      />
                  </Header>
                  <Content style={{ padding: '0 50px' }}>
                      {children}
                  </Content>
                  <Footer style={{ textAlign: 'center' }}>
                      Created at 2025 by Boris FatBoy
                  </Footer>
              </Layout>
          </body>
      </html>
  );
}
